The debugging for my codon files took much longer than io was planning for resulting in this being handed in 2 days late, the main issues were forgetting to run export CODON_PYTHON=/path/to/libpython.X.Y.so to allow access to matplotlib resulting in me originally changing the methods in dbg_codon.py way to much frankenstiening the code and leading to way to many different errors. eventually I realized the issue and was then trying to us an @python header in main to change the recursion limit but that wasnt needed. The sementation fault while running data 4 required me to run ulimit -s 8192000 again, but it took a long time to find because other errors were present when I tried this originally.